# TARGET=libxthread.so
# OBJS=xthread.o
# # 编译为动态链接库
# LDFLAGS=-shared
# # 加上 fPIC 选项生成的动态库，显然是位置无关的
# # -std=c++11，支持C++11标准；
# # -std=gnu++11，支持C++11标准和GNU扩展特性；
# CXXFLAGS=-fPIC -std=gnu++11 
# $(TARGET):$(OBJS)
# 	$(CXX) $(LDFLAGS) $^ -o $@
# clean:
# 	$(RM) $(TARGET) $(OBJS)
# .PHONY:clean

# xthread makefile
LIBTYPE:=.so
include ../makefile.mk